---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-mem-limit-range
  namespace: UNDEFINED
spec:
  limits:
  - default:
      cpu: 100m
      memory: 256Mi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    # The maximum amount of CPU and memory burst that a container can
    # make as a ratio of its limit over request.
    # This helps enforce the limit and request to be the same.
    # maxLimitRequestRatio:
    #   memory: "1"
    #   cpu: "1"
    # type: Container
