---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../deployment

patches:
# Patch the UNDEFINED kind from Deployment into a DaemonSet
- target:
    kind: Deployment
  patch: |-
    - op: replace
      path: /kind
      value: StatefulSet
    - op: add
      path: /spec/serviceName
      value: UNDEFINED
