apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: registry-docker-hub
  namespace: UNDEFINED
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .dockerconfigjson | toString }}"
    name: registry-docker-hub
    creationPolicy: Owner
  data: []
