---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../deployment

patches:
- target:
    kind: Deployment
  patch: |-
    - op: replace
      path: /kind
      value: ReplicaSet
