---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: UNDEFINED
  namespace: UNDEFINED
  labels:
    k8s-app: UNDEFINED
spec:
  selector:
    matchLabels:
      name: UNDEFINED
  template:
    metadata:
      labels:
        name: UNDEFINED
    spec:
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: UNDEFINED
        image: UNDEFINED@sha256:abcd1234
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 10001
          runAsGroup: 10001
    terminationGracePeriodSeconds: 30
