---
apiVersion: v1
kind: Service
metadata:
  name: UNDEFINED
  namespace: UNDEFINED
spec:
  selector:
    app.kubernetes.io/name: UNDEFINED
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
