---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-store
  namespace: UNDEFINED
  labels:
    app.kubernetes.io/instance: secret-store
    app.kubernetes.io/name: secret-store
    app.kubernetes.io/part-of: secret-store
