---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: UNDEFINED
  namespace: UNDEFINED
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: UNDEFINED
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: UNDEFINED
            port:
              number: 80
