apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: UNDEFINED
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: UNDEFINED
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: UNDEFINED
            name: UNDEFINED
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/10 * * * *'
status: {}
