---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- path: deployment.yaml
  target:
    group: apps
    kind: Deployment
- path: statefulset.yaml
  target:
    group: apps
    kind: StatefulSet
- target:
    group: apps
    kind: Deployment
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/securityContext
      value:
        capabilities:
          # Pods should not run containers with default capabilities assigned
          # Reference: https://docs.fugue.co/FG_R00493.html
          drop: [ALL]
        # Pods should not run containers as the root user
        # Reference: https://docs.fugue.co/FG_R00490.html
        runAsNonRoot: true
- path: securitycontext.yaml
  target:
    group: apps
    kind: StatefulSet
