  # FG_R00495: Pod seccomp profile should be set [Medium]
  #           https://docs.fugue.co/FG_R00495.html
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: security
spec:
  selector: {}
  serviceName: security
  template:
    metadata:
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: "runtime/default"
